export const PUBLIC_PAGES = [
  {
    path: '/features',
    group: 'Product',
    title: 'Fleet management, brought into one operational view',
    summary: 'Explore the connected workflows represented in the Fleet Drive AI Demo, from vehicle visibility to maintenance planning.',
    status: 'Real Demo Functions',
    sections: [
      ['Fleet visibility', 'Inspect vehicle status, driver assignments, fuel levels, mileage and simulated location data.'],
      ['Operational response', 'Move from dashboard indicators to vehicle and driver detail views without losing context.'],
      ['Decision support', 'Use calculated demo metrics, maintenance indicators and scenario alerts to understand fleet conditions.'],
    ],
  },
  {
    path: '/pricing',
    group: 'Product',
    title: 'Illustrative pricing for product discovery',
    summary: 'The packages shown in this Demo help communicate possible product tiers. They are not final commercial offers or quotations.',
    status: 'Illustrative Demo Pricing',
    sections: [
      ['Starter concept', 'A possible entry tier for smaller fleets that need visibility, alerts and standard reporting.'],
      ['Operations concept', 'A possible tier for growing teams that need maintenance, geofencing and deeper oversight.'],
      ['Enterprise concept', 'A future commercial conversation for integrations, deployment planning and support requirements.'],
    ],
  },
  {
    path: '/mobile-apps',
    group: 'Product',
    title: 'Mobile access is on the commercial roadmap',
    summary: 'Fleet Drive AI mobile applications are planned, but no app is currently published in an application store.',
    status: 'Planned Commercial Feature',
    sections: [
      ['Operations on the move', 'The intended experience includes vehicle status, alerts and key fleet summaries.'],
      ['Driver workflows', 'Future mobile workflows may support task visibility and operational communication.'],
      ['Availability', 'No iOS or Android download is offered by this Demo.'],
    ],
  },
  {
    path: '/changelog',
    group: 'Product',
    title: 'Demo changelog',
    summary: 'A concise record of the working capabilities introduced as the Fleet Drive AI Demo evolves.',
    status: 'Demo Documentation',
    sections: [
      ['Authentication foundation', 'Real registration, login, protected routes, logout and session restoration through Express.'],
      ['Frontend foundation', 'Responsive layouts, shared design tokens, API handling and resilient loading and error states.'],
      ['Public website', 'A complete public experience with transparent product, pricing, mobile and prototype disclosures.'],
    ],
  },
  {
    path: '/roadmap',
    group: 'Product',
    title: 'A roadmap grounded in verified capability',
    summary: 'Roadmap items communicate direction only. They are not delivery commitments or claims of production availability.',
    status: 'Planned Commercial Features',
    sections: [
      ['Data integrations', 'Evaluate production telemetry providers and hardware integration requirements.'],
      ['Mobile workflows', 'Design and validate field-ready mobile experiences before store publication.'],
      ['Operational intelligence', 'Progress from deterministic demo indicators to validated commercial analytics and AI models.'],
    ],
  },
  {
    path: '/solutions',
    group: 'Solutions',
    title: 'Flexible fleet operations without a sector lock-in',
    summary: 'Fleet Drive AI is designed as a sector-neutral operating layer for teams that manage vehicles, people and service schedules.',
    status: 'Product Direction',
    sections: [
      ['Visibility', 'Bring vehicles and drivers into a shared operational picture.'],
      ['Control', 'Organise maintenance, alerts and location-based operating rules.'],
      ['Evidence', 'Turn activity history and fleet data into useful operational reporting.'],
    ],
  },
  {
    path: '/solutions/fleet-tracking',
    group: 'Solutions',
    title: 'Fleet tracking',
    summary: 'See simulated vehicle positions, movement states and operational context in the working Demo.',
    status: 'Simulated Data',
    sections: [
      ['Map visibility', 'The Demo renders location scenarios from its simulated fleet data source.'],
      ['Vehicle context', 'Status, driver, fuel, mileage and recent activity remain connected to each vehicle.'],
      ['Commercial boundary', 'The Demo is not connected to production GPS hardware.'],
    ],
  },
  {
    path: '/solutions/driver-management',
    group: 'Solutions',
    title: 'Driver management',
    summary: 'Review driver profiles, assignments and demonstration performance indicators in one place.',
    status: 'Real Demo Function',
    sections: [
      ['Driver records', 'Structured profiles provide licence, contact and assignment context.'],
      ['Performance scenarios', 'Simulated scores and trends demonstrate intended analytical workflows.'],
      ['Responsible use', 'Demo values are fictional and must not be treated as employment or safety decisions.'],
    ],
  },
  {
    path: '/solutions/maintenance',
    group: 'Solutions',
    title: 'Maintenance planning',
    summary: 'Surface service intervals and mileage-based maintenance conditions before they become operational surprises.',
    status: 'Real Demo Function',
    sections: [
      ['Service visibility', 'Compare current mileage with service history and configured intervals.'],
      ['Prioritisation', 'Demo indicators help distinguish upcoming, due and overdue work.'],
      ['Next step', 'Persistent work orders and supplier workflows remain future commercial capabilities.'],
    ],
  },
  {
    path: '/solutions/geofencing',
    group: 'Solutions',
    title: 'Geofencing',
    summary: 'Create Demo boundaries, check stored vehicle positions and inspect entry or exit events produced by telemetry processing.',
    status: 'Real Demo Function',
    sections: [
      ['Zone design', 'The intended workflow supports operational areas and monitored boundaries.'],
      ['Event awareness', 'The Express backend persists supported entry and exit events when telemetry crosses a configured boundary.'],
      ['Current Demo', 'Boundary processing is functional; production device enforcement and external notifications are not claimed.'],
    ],
  },
  {
    path: '/solutions/reports',
    group: 'Solutions',
    title: 'Fleet reporting',
    summary: 'Reporting views consume persisted maintenance and telemetry-history reports from the current Express API.',
    status: 'Real Demo Function',
    sections: [
      ['Operational summaries', 'Bring status, distance, driver and maintenance signals together.'],
      ['Traceable sources', 'Commercial reports should originate from backend history rather than hard-coded KPI values.'],
      ['Current boundary', 'Production exports and scheduled report delivery are not yet available.'],
    ],
  },
  {
    path: '/about',
    group: 'Company',
    title: 'Built to make fleet operations easier to understand',
    summary: 'Fleet Drive AI is the intended commercial product. This repository is its working demonstration environment.',
    status: 'Product Identity',
    sections: [
      ['The product', 'Fleet Drive AI aims to unify vehicle, driver and maintenance operations in a clear, dependable system.'],
      ['The Demo', 'Fleet Drive AI Demo proves workflows with real frontend and Express behavior plus simulated source data.'],
      ['The standard', 'Claims, integrations and commercial readiness remain explicit so the product can earn trust honestly.'],
    ],
  },
  {
    path: '/careers',
    group: 'Company',
    title: 'Careers',
    summary: 'There are no published Fleet Drive AI vacancies in this Demo environment.',
    status: 'No Open Listings',
    sections: [
      ['Future opportunities', 'Roles may be published here as the commercial product and team develop.'],
      ['No speculative applications', 'The Demo does not collect CVs or personal recruitment information.'],
      ['Authenticity', 'Only formally published roles should be treated as available.'],
    ],
  },
  {
    path: '/blog',
    group: 'Company',
    title: 'Product notes',
    summary: 'Long-form Fleet Drive AI articles are planned. The Demo currently publishes its progress through the changelog and repository documentation.',
    status: 'Planned Content',
    sections: [
      ['Product development', 'Future notes will explain verified improvements and implementation decisions.'],
      ['Fleet practice', 'Planned articles may explore maintenance, driver operations and telemetry design.'],
      ['No fabricated publication', 'This page does not present placeholder articles as published editorial work.'],
    ],
  },
  {
    path: '/contact',
    group: 'Company',
    title: 'Start a Fleet Drive AI conversation',
    summary: 'Use the registration flow to explore the Demo. Commercial contact channels will be published when they are ready to receive enquiries.',
    status: 'Demo Access Available',
    action: { label: 'Create Demo Account', to: '/register' },
    sections: [
      ['Product exploration', 'Register for the working Demo and inspect its current vehicle and driver workflows.'],
      ['Commercial enquiries', 'No unverified sales address or lead-capture backend is presented here.'],
      ['Support', 'Review the support page for the current Demo support boundary.'],
    ],
  },
  {
    path: '/partners',
    group: 'Company',
    title: 'Partnerships',
    summary: 'Fleet Drive AI does not claim hardware, channel or public-sector partnerships in this Demo.',
    status: 'Future Commercial Program',
    sections: [
      ['Integration partners', 'Future work may include vetted telemetry, mapping and operational systems.'],
      ['Delivery partners', 'Implementation relationships will be described only after they are formally established.'],
      ['No implied endorsement', 'Logos or partner claims are intentionally absent from this Demo.'],
    ],
  },
  {
    path: '/documentation',
    group: 'Resources',
    title: 'Demo documentation',
    summary: 'The repository contains implementation audits, backend stabilization notes, the API contract and frontend work-package records.',
    status: 'Available in Repository',
    sections: [
      ['Repository audit', 'Documents the original design reference, legacy application, Express backend and historical Postman contract.'],
      ['API reference', 'Defines implemented and contract-only endpoints, authentication, request shapes and limitations.'],
      ['Implementation records', 'Each completed work package records behavior, validation and unresolved boundaries.'],
    ],
  },
  {
    path: '/support',
    group: 'Resources',
    title: 'Demo support',
    summary: 'This environment does not claim a commercial support desk, service-level agreement or production uptime commitment.',
    status: 'Demo Support Boundary',
    sections: [
      ['Access issues', 'Demo accounts persist in the configured SQLite database. Clearing or replacing that database requires registration again.'],
      ['API configuration', 'The frontend expects VITE_API_URL to point to the Express API root.'],
      ['Commercial support', 'Support channels and response commitments will be defined before commercial release.'],
    ],
  },
  {
    path: '/api-reference',
    group: 'Resources',
    title: 'API reference',
    summary: 'The current Demo exposes real authentication and vehicle-list endpoints through Express.',
    status: 'Verified Demo Contract',
    sections: [
      ['Authentication', 'POST /api/auth/register, POST /api/auth/login and GET /api/auth/me.'],
      ['Vehicles', 'GET /api/vehicles returns the current simulated backend fleet.'],
      ['Operational APIs', 'Vehicles, drivers, maintenance, alerts, geofences, routes and reports are implemented in the current Express Demo API.'],
    ],
  },
  {
    path: '/status',
    group: 'Resources',
    title: 'Service status',
    summary: 'No public production status service or commercial uptime history exists for Fleet Drive AI yet.',
    status: 'Demo Environment Only',
    sections: [
      ['Local frontend', 'Availability depends on the locally running Vite development server.'],
      ['Local API', 'Authentication and fleet data depend on the locally running Express process.'],
      ['Commercial monitoring', 'External monitoring and published uptime targets are future operational requirements.'],
    ],
  },
  {
    path: '/community',
    group: 'Resources',
    title: 'Community',
    summary: 'A public Fleet Drive AI user community has not been launched.',
    status: 'Future Commercial Program',
    sections: [
      ['Product feedback', 'Structured feedback channels may be introduced as the Demo reaches broader evaluators.'],
      ['Knowledge sharing', 'Documentation and practical fleet-operation guidance are planned foundations.'],
      ['No implied membership', 'The Demo does not claim an existing customer or partner community.'],
    ],
  },
  {
    path: '/privacy',
    group: 'Legal',
    title: 'Privacy policy',
    summary: 'This Demo uses local browser storage for authentication and does not present itself as a production data-processing service.',
    status: 'Demo Policy',
    sections: [
      ['Authentication data', 'Demo usernames, names and bcrypt password hashes are stored in the configured SQLite Demo database. Passwords are not returned by the API.'],
      ['Browser storage', 'Session tokens use sessionStorage unless remember me is selected, in which case localStorage is used.'],
      ['Simulated records', 'Fleet, driver and activity records shown in the Demo are fictional demonstration data.'],
    ],
  },
  {
    path: '/terms',
    group: 'Legal',
    title: 'Terms of Demo use',
    summary: 'Fleet Drive AI Demo is provided for evaluation and demonstration, not for live fleet operations or safety-critical decisions.',
    status: 'Demo Terms',
    sections: [
      ['Evaluation use', 'Use the Demo to inspect product concepts and working software behavior.'],
      ['No production reliance', 'Do not rely on simulated locations, alerts, scores or maintenance indicators for real operations.'],
      ['No commercial commitment', 'Demo content does not create a service agreement, warranty or pricing commitment.'],
    ],
  },
  {
    path: '/cookies',
    group: 'Legal',
    title: 'Cookie policy',
    summary: 'Fleet Drive AI Demo does not intentionally use advertising or analytics cookies.',
    status: 'Demo Policy',
    sections: [
      ['Authentication storage', 'The Demo uses browser web storage for JWT session behavior rather than a tracking cookie.'],
      ['Third-party media', 'Public visual assets and map tiles may be requested from their respective hosts when displayed.'],
      ['Future changes', 'Any future analytics or cookie use should be disclosed before deployment.'],
    ],
  },
  {
    path: '/prototype',
    group: 'Legal',
    title: 'Prototype and Demo disclosure',
    summary: 'Fleet Drive AI is the intended commercial product. Fleet Drive AI Demo is a working full-stack demonstration, not a production fleet service.',
    status: 'Important Disclosure',
    sections: [
      ['Real Demo functions', 'Authentication, route protection, API communication and available fleet screens execute as working software.'],
      ['Simulated data', 'Fleet telemetry, locations, drivers, alerts and scenarios are generated or curated for demonstration.'],
      ['Planned capabilities', 'Mobile apps, hardware, production AI, commercial support and production-scale integrations are future product work.'],
    ],
  },
];

export const PUBLIC_PAGE_BY_PATH = Object.fromEntries(PUBLIC_PAGES.map((page) => [page.path, page]));
